# Generated by Django 4.1.6 on 2023-02-04 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_rename_desciption_product_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='thumbnail',
            new_name='thumbbnail',
        ),
    ]
