# Generated by Django 4.1.6 on 2023-02-05 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_category_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('-date_added',)},
        ),
    ]
